spring:
  application:
    name: cloud-admin-menu-server
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://${cloud.admin.datasource.url:localhost:3306}/cloud-admin?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: ${cloud.admin.datasource.username:root}
    password: ${cloud.admin.datasource.password:Admin1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: MyHikariCP
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #redis
  redis:
    host: ${cloud.admin.redis.host:localhost}
    password: ${cloud.admin.redis.password:Admin1234}
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  # 注册中心
  cloud:
    nacos:
      discovery:
        server-addr: ${cloud.admin.discovery.server-addr:localhost:8848}
        namespace: aff3eac8-1bcc-4272-ba98-94b54fb1c016
        group: cloud-admin-group
    sentinel:
      transport:
        port: 8721
        dashboard: ${cloud.admin.sentinel.dashboard:localhost:8080}
        heartbeat-interval-ms: 3000
      filter:
        url-patterns: /**

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
      #更新 插入 查询策略
      update-strategy: ignored
      insert-strategy: ignored
      select-strategy: ignored
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:
    pageSize=countSql
  offset-as-page-num: true
  row-bounds-with-count: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 1050

# jetcache 操作redis
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: true
  hiddenPackages: com.hb0730.cloud.admin.server.router
  local:
    default:
      limit: 100
      keyConvertor: fastjson
      expireAfterWriteInMillis: 100000
  remote:
    cloud-admin:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      uri: redis://${spring.redis.password}@${spring.redis.host}:${spring.redis.port}

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:1010/oauth/token
      user-authorization-uri: http://localhost:1010/oauth/authorize
    resource:
      token-info-uri: http://localhost:1010/oauth/check_token

cloud:
  admin:
    discovery:
      server-addr: localhost:8848
    sentinel:
      dashboard: localhost:8408
    rocketmq:
      name-server: localhost:9876
    datasource:
      url: localhost:3306
      username: root
      password: Admin123
    redis:
      host: localhost
      password: Admin123
