spring:
  application:
    name: cloud-admin-user-post-server
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    platform: mysql
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      connection-test-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${cloud.admin.datasource.url:localhost:3306}/cloud-admin?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: ${cloud.admin.datasource.username:root}
      password: ${cloud.admin.datasource.password:Admin1234}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    generator:
      write_numbers_as_strings: true

  #redis
  redis:
    host: ${cloud.admin.redis.host:localhost}
    password: ${cloud.admin.redis.password:Admin1234}
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  # 注册中心
  cloud:
    nacos:
      discovery:
        server-addr: ${cloud.admin.discovery.server-addr:localhost:8848}
        namespace: aff3eac8-1bcc-4272-ba98-94b54fb1c016
        group: cloud-admin-group
    sentinel:
      transport:
        port: 8721
        dashboard: ${cloud.admin.sentinel.dashboard:localhost:8080}
        heartbeat-interval-ms: 3000

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
      #更新 插入 查询策略
      update-strategy: ignored
      insert-strategy: ignored
      select-strategy: ignored
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:
    pageSize=countSql
  offset-as-page-num: true
  row-bounds-with-count: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 1170

# jetcache 操作redis
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: true
  hiddenPackages: com.hb0730.cloud.admin.server.user.post
  local:
    default:
      limit: 100
      keyConvertor: fastjson
      expireAfterWriteInMillis: 100000
  remote:
    cloud-admin:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      uri: redis://${spring.redis.password}@${spring.redis.host}:${spring.redis.port}

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:1010/oauth/token
      user-authorization-uri: http://localhost:1010/oauth/authorize
    resource:
      token-info-uri: http://localhost:1010/oauth/check_token
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: BASIC
  okhttp:
    enabled: true
  httpclient:
    enabled: false

cloud:
  admin:
    discovery:
      server-addr: localhost:8848
    sentinel:
      dashboard: localhost:8408
    rocketmq:
      name-server: localhost:9876
    datasource:
      url: localhost:3306
      username: root
      password: Admin123
    redis:
      host: localhost
      password: Admin123
seata:
  enabled: true
  application-id: cloud-admin-user-post-seata
  tx-service-group: cloud-admin-tx-steata-group # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  client:
    rm-report-success-enable: true
    rm-table-meta-check-enable: false # 自动刷新缓存中的表结构（默认false）
    rm-report-retry-count: 5 # 一阶段结果上报TC重试次数（默认5）
    rm-async-commit-buffer-limit: 10000 # 异步提交缓存队列长度（默认10000）
    rm:
      lock:
        lock-retry-times:    30 # 校验或占用全局锁重试次数（默认30）
        lock-retry-policy-branch-rollback-on-conflict: true # 分支事务与其它全局回滚事务冲突时锁策略（优先释放本地锁让回滚成功）
        lock-retry-interval: 10 # 校验或占用全局锁重试间隔（默认10ms）
    tm-commit-retry-count:   3 # 一阶段全局提交结果上报TC重试次数（默认1次，建议大于1）
    tm-rollback-retry-count: 3 # 一阶段全局回滚结果上报TC重试次数（默认1次，建议大于1）
    undo:
      undo-data-validation: true # 二阶段回滚镜像校验（默认true开启）
      undo-log-serialization: jackson # undo序列化方式（默认jackson）
      undo-log-table: undo_log  # 自定义undo表名（默认undo_log）
    log:
      exceptionRate: 100 # 日志异常输出概率（默认100）
    support:
      spring:
        datasource-autoproxy: true
  service:
    vgroup-mapping: default  # TC 集群（必须与seata-server保持一致）
    enable-degrade: false # 降级开关
    disable-global-transaction: false # 禁用全局事务（默认false）
    grouplist: 47.96.79.54:8091
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true # 客户端事务消息请求是否批量合并发送（默认true）
  registry:
    file:
      name: file.conf
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      namespace: "0842cd23-b1ca-48f2-abca-67225d35248b"
      cluster: default
  config:
    file:
      name: file.conf
    type: nacos
    nacos:
      namespace: "0842cd23-b1ca-48f2-abca-67225d35248b"
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
